version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: arsalan77x
      POSTGRES_PASSWORD: guclagani77x
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://arsalan77x:guclagani77x@db:5432/mydatabase
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
